### ISSUE TITLE
bower main files order

### ISSUE THREAD

**Issue by Fredx87** [freegroup/draw2d_js.bower#1]
I'm using a gulp task to automatically build a unique file from all the required third party libraries, using main-bower-files.
This gulp plugin include each library with its dependencies in the right order reading the library dependencies in the the bower.json file.
Since draw2d bower repository include third party patched libraries, and for these libraries it doesn't use bower dependency, the libraries are included in the wrong order, because the plugin uses the order of the files that are declared in the main section of the bower.json file.

So I think that the order of the "main" section of the bower.json file should follow the order of the inclusion of the scripts in the html page, like this:
```
"main": [
                "dist/jquery.autoresize.js",
                "dist/jquery-touch_punch.js",
                "dist/jquery.contextmenu.js",
                "dist/patched_raphael.js",
                "dist/rgbcolor.js",
                "dist/patched_canvg.js",
                "dist/patched_Class.js",
                "dist/json2.js",
                "dist/pathfinding-browser.min.js",
                "dist/StackBlur.js",
                "dist/draw2d.js"
            ]
```

**Comment by freegroup** [comment]
Dear

thanks for the fix. 
Integrated.
